//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int NumWorker { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Fingerprint { get; set; }
        public Nullable<bool> IsEnter { get; set; }
        public Nullable<double> NunHours { get; set; }
        public Nullable<double> Salery { get; set; }
        public Nullable<System.DateTime> TimeEnter { get; set; }
        public Nullable<System.DateTime> TimeExit { get; set; }
        public Nullable<int> Place { get; set; }
    }
}
